import {
  AiOutlineOrderedList,
  AiOutlineUnorderedList,
  AiOutlineBold,
  AiOutlineItalic,
  AiOutlineUnderline,
  AiOutlineBgColors,
  AiOutlineLink,
  AiOutlineFontSize,
  AiOutlineFontColors,
  AiOutlineAlignCenter,
  AiOutlineAlignLeft,
  AiOutlineAlignRight,
  AiOutlineStrikethrough,
} from "react-icons/ai";
import {
  BsTextIndentLeft,
  BsFonts,
  BsFileBreak,
  BsCode,
  BsCardText,
  BsImages,
} from "react-icons/bs";
import { BiRedo, BiUndo, BiLink, BiUnlink } from "react-icons/bi";
import {
  TbHeading,
  TbAlignRight,
  TbAlignLeft,
  TbAlignJustified,
  TbAlignCenter,
  TbIndentIncrease,
  TbIndentDecrease,
  TbEraser,
  TbSubscript,
  TbSuperscript,
} from "react-icons/tb";
import React from "react";

export default {
  background: <AiOutlineBgColors />,
  bold: <AiOutlineBold />,
  link: <BiLink />,
  font: <BsFonts />,
  fontSize: <AiOutlineFontSize />,
  color: <AiOutlineFontColors />,
  heading: <TbHeading />,
  indent: <TbIndentIncrease />,
  hr: <BsFileBreak />,
  html: <BsCode />,
  image: <BsImages />,
  list: <AiOutlineUnorderedList />,
  orderedList: <AiOutlineOrderedList />,
  p: <BsCardText />,
  italic: <AiOutlineItalic />,
  justifyCenter: <TbAlignCenter />,
  justifyFull: <TbAlignJustified />,
  justifyLeft: <TbAlignLeft />,
  justifyRight: <TbAlignRight />,
  outdent: <TbIndentDecrease />,
  redo: <BiRedo />,
  removeFormat: <TbEraser />,
  strike: <AiOutlineStrikethrough />,
  subscript: <TbSubscript />,
  superscript: <TbSuperscript />,
  underline: <AiOutlineUnderline />,
  undo: <BiUndo />,
  unlink: <BiUnlink />,
};
